### ISSUE TITLE
E2E Testing (TM-2): Filters for thesis list

### ISSUE THREAD

**Issue by RiccardoVukovic320029** [lorenzobn/polito-se2-23-08#12]
Need for backend functions that retrieve lists of  research groups,  titles, supervisors and subjects in order to develop proposal filters

**Comment by ghost** [comment]
Hello Riccardo,

Thank you for opening this issue. Can you please specify more details about what you need so we can correctly address this?

**Comment by RiccardoVukovic320029** [comment]
Hi Lorenzo,
in order to develop a filtering function for the thesis list, it is needed to create backend routes that retrieves:
1. a list of all existing research groups
2. a list of all existing supervisors
3. a list of all existing subjects
A user, pressing on one of the filter keywords in the main page's sidebar, will be able to open a menu that will show a list coherent with the selected filter and will be able to choose one of the list's element.
For example: the user selects the keyword "By research group", a sidebar menu will show up containing all research groups retrieved from the database. Eventually the user will choose  for example "research group A" and the thesis list will be filtered by means of this keyword.

P.S. it's still to be clarified what 'filter by title' means, since the title is most probably unique and the searchbar allows to make this type of filter way better

**Comment by ghost** [comment]
Hello Riccardo,

The [latest commit](https://github.com/teamEightTO/polito-se2-23-08/commit/74df56c933e727a5338b1350946af607090007ec) solved this issue:

1) For the research groups, you can call the endpoint `/groups` and it will give you all the GROUPS in the DB
2) For the supervisors, you can call the endpoint `/cosupervisors` and it return the list of all internal cosupervisors (since they are all teachers, they can also be supervisors)
3) I would replace subject button in the sidebar with STATUS. Since we have to only search for the THESIS_PROPOSALS fields, the status is the only one missing. No need for an additional API because the status already comes in `/thesis-proposals`

**Comment by ghost** [comment]
Done with latest commit. Closing.
