### ISSUE TITLE
E2E Testing (TM-4): Dynamic rendering of received-applications view

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#28]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/05358be9-1166-472c-8590-3130174f0ab1)
As @lorenzobn pointed out, when we click on the view applications button, we can see the application which is only 1. But if we have more than one application, we cannot see it. 

As per the design suggestion in the last issue, it's best to have all the applications displayed in the application tab irrespective of it's association to the thesis list for a much simpler design and implementation.

**Comment by ghost** [comment]
We clarified this together with @RiccardoVukovic320029 . This should be the process:

1) Professor logs in
2) Navigates to `/received-applications`
3) Clicks on one of the thesis he/she is supervising
4) The view now shows all the student cards with the relevant informations to decide accept/reject

Since all the steps till the third are done, only dynamic rendering of the 4th part is missing.
