### ISSUE TITLE
Wrong behavior after application has been accepted/rejected

### ISSUE THREAD

**Issue by valerianoCarlos** [lorenzobn/polito-se2-23-08#51]
There was an issue regarding buttons that were not being disabled after the professor accepted/rejected an application, allowing the professor to click on the button again but only displaying an error from the server. The behavior should be prevented by disabling the buttons or removing them after a decision on an application has been taken.

**Comment by ghost** [comment]
Hello @valerianoCarlos,

Thank you for your feedback. This will be addressed soon.

**Comment by ghost** [comment]
Hello guys,

I did some changes to the backend to address this issue.
Login as a Professor (Enrico Bini for example) and pick the first application. If you click on accept/reject everything works fine. As soon as the application is accepted/rejected, the professor shouldn't be able to decide it anymore. In fact, if you send another update request to the server it should return a `400 - Bad request` response. Currently, the toast message doesn't give the correct result but if you look in the Network table everything works okay.

The point here is that, client-side, these buttons (ACCEPT  / REJECT) should be removed, since there is no possible action after the decision has been made.

@SahandGhavami @Mieti What do you guys think?
