### ISSUE TITLE
E2E Testing (TM - 7): When I change the virtual clock in the future, no proposals should exist in the Proposal Tab

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#66]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/ecfbb51d-90aa-4f2c-b054-0d450deefa3d)
I am currently in 2025 and I still see the proposals in the proposal tab

**Comment by ghost** [comment]
I believe the behaviour must be investigated better. In the Proposals section, a teacher should see the proposals he/she created. Even if you are in 2025, those proposals were still created in some moment in the past by a teacher. 

I think that those two scenarios are possible:
1) Once the deadline of the proposal is passed, the proposal is moved automatically to archived section. We don't see the proposal in the Proposals tab anymore.
2) We see all the thesis proposals in the Proposals tab.

Now, since we haven't fully implemented the archive, right now this issue must be better investigated considering also that we should finish the archive functionality and then address this issue.

**Comment by s316741** [comment]
This is resolved, thank you.
