### ISSUE TITLE
TM - 10 (Delete Proposal) - Proposal should not delete once an application has been accepted

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#87]
Currently, when I am accepting a student's application and then deleting it, it still deleted.

We should have a conditional message:
1. Are you sure you want to delete the proposal (for when there is no application decision)
2. You cannot delete this proposal as application decision has been taken

**Comment by ghost** [comment]
Hello,

I checked and the server now handles the case correctly. In fact, when there is already an application for a proposal and the professor tries to delete it, the response in the API call is: _Cannot delete this proposal because there is an accepted application_

The message must be returned in the Toast Message Client-side

**Comment by SahandGhavami** [comment]
Hello all,
It is fixed now.
